;; Wulfram II compatibility profile for DxWrapper v1.8.8600.25.
;; https://github.com/elishacloud/dxwrapper

[General]
RealDllPath                = AUTO
WrapperMode                = AUTO
LoadCustomDllPath          = w2reg.dll
IncludeProcess             = wulfram2.exe
DisableLogging             = 0

[Compatibility]
Dd7to9                     = 0
D3d8to9                    = 0
D3d9to9Ex                  = 0
D3d9on12                   = 0
DDrawCompat                = 0
Dinputto8                  = 0
ConfigureDpiAwareness      = 0
DisableGameUX              = 0
EnableDdrawWrapper         = 0
EnableD3d9Wrapper          = 0
EnableDinput8Wrapper       = 0
EnableDsoundWrapper        = 0
FixPerfCounterUptime       = 0
HandleExceptions           = 0
SingleProcAffinity         = 0

[ddraw]
DdrawOverrideBitMode       = 0
DdrawUseDirect3D9Caps      = 0

[Dd7to9]
DdrawEmulateSurface        = 1
DdrawEmulateLock           = 1
DdrawUseShadowSurface      = 1
DdrawKeepAllInterfaceCache = 1
DdrawForceMipMapAutoGen    = 1
DdrawClampVertexZDepth     = 1
DdrawFilterActivateApp     = 1
DdrawLinearTextureFilter   = 1
DdrawUseNativeResolution   = 1
DdrawIntegerScalingClamp   = 0
DdrawMaintainAspectRatio   = 1

[d3d9]
AnisotropicFiltering       = 16
AntiAliasing               = 0
EnableVSync                = 1
ForceVsyncMode             = 1
LimitPerFrameFPS           = 60
EnableWindowMode           = 1
WindowModeBorder           = 0
FullscreenWindowMode       = 1
HideWindowFocusChanges     = 0
EnableCursorClip           = 1
ForceMixedVertexProcessing = 1
DisableMaxWindowedMode     = 1
GraphicsHybridAdapter      = 1

[dinput8]
FilterNonActiveInput       = 1
FixHighFrequencyMouse      = 1
