AltTabFix = keepvidmem
# AlternatePixelCenter = off
# Antialiasing = off
# BltFilter = point
# ColorKeyMethod = alphatest(1)
# ConfigTransparency = alpha(90)
DepthFormat = 32
# DisplayAspectRatio = app
#DisplayFilter = anti-aliasing\aa-shader-4.o.cgp
#FullscreenMode = borderless
# FontAntialiasing = app
# FpsLimiter = off
# MousePollingRate = native
# MouseSensitivity = desktop(100)
# PresentDelay = on(10)
# RenderColorDepth = 32
ResolutionScale = display(1)
# ResolutionScaleFilter = point
SpriteAltPixelCenter = off
# SpriteDetection = off
# SpriteFilter = app
# SpriteTexCoord = app
# StatsPosX = right
# StatsPosY = top
StatsTransparency = alpha(100)
ThreadPriorityBoost = on
# TextureFilter = app
VertexBufferMemoryType = sysmem
# VertexFixup = gpu
# ViewportEdgeFix = off
VSync = off
